const checklist = 'checklists/';
const searchOnlineChecklist = 'searchonlinechecklist/';

export const routerConstants = {
    defaultRoute: '/' + 'assigned/' + 'viewassigned',
    addChecklist: checklist + 'addchecklist',
    modifyChecklist: checklist + 'modifychecklist',
    searchChecklist: checklist + 'searchchecklist/',
    searchChecklistResults: checklist + 'searchchecklist/' + 'checklistResults',
    searchControl: checklist + 'searchcontrol/',
    searchControlResults: checklist + 'searchcontrol/' +  'searchcontrolresults',
    viewchecklistControl: checklist +  'viewChecklistsControls',
    order: checklist + 'order',
    addControl: checklist + 'addcontrol',
    modifycontrols : checklist + 'modifycontrols',
    reports: checklist + 'reports',
    displayreports: checklist + 'reportresults',
    assigned : 'assigned/',
    viewassigned: 'assigned/' + 'viewassigned',
    manage: 'managed',
    checklistManager: 'manage' + 'checklistmanagers',
    scheduleChecklist: 'managed/' + 'schedulechecklist',
    scheduleChecklistResults: 'managed/' + 'schedulechecklist/' + 'schedulechecklistresults',
    checklistScheduled: 'managed/' + 'schedulechecklist/' + 'schedulechecklistresults/' + 'checklistscheduled',
    newChecklistSchedule: 'managed/' + 'newchecklistschedule',
    editChecklistSchedule: 'managed/' + 'editchecklistschedule',
    searchOnlineChecklistt: searchOnlineChecklist,
    searchonlinechecklistResult: searchOnlineChecklist  + 'results',
    onlineChecklistAssignment: searchOnlineChecklist + '/assignments',
    ModifyManagerAssignment: searchOnlineChecklist + 'employeeassignments/' + 'modifymanagerassignment',
    searchonlinechecklistControls: searchOnlineChecklist  + 'checklistControls',
    viewUpdateOnlineControls: searchOnlineChecklist  + 'viewControl',
    updateChecklistStatus: searchOnlineChecklist + 'updatecheckliststatus',
    attachments: searchOnlineChecklist + 'attachments',
    comments: searchOnlineChecklist + 'comments'
};
